### ISSUE TITLE
Editing of date and time work wrong

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1219] opened 2020-11-04 13:12 UTC
I typed into a DATE field: 10/11/2020
I want to change this into 10/09/2020
Ok, I move the cursor after ’9’ and press Backspace twice, now the date shows 10/12/20  

The same happens with TIME entry

**Comment by SteRiccio** [comment] 2020-11-04 13:43
duplicate of #1061

**Closed by SteRiccio** 2020-11-04 13:43 UTC
