### ISSUE TITLE
Error 500: Published survey, add new attribute, and delete survey

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1136] opened 2020-08-28 13:24 UTC
I had imported survey, no errors. It was published.
The I added a new multientry code attribute.
Then deleted this survey. Error 500 shows up. 
So this was not NOT republished after adding this attribute.

![image](https://user-images.githubusercontent.com/45661798/91565572-173e4f80-e94b-11ea-9477-1b862e172c36.png)

**Comment by SteRiccio** [comment] 2020-11-12 10:28
duplicate of #1215

**Closed by SteRiccio** 2020-11-12 10:28 UTC
Labels: bug
